;Logic necessary to run through test suite
(load "interpret.scm")
(load "simpleParser.scm")
(require rackunit)

(check-eq? (interpretCode "tests/1") 150)
(check-eq? (interpretCode "tests/2") -4)
(check-eq? (interpretCode "tests/3") 10)
(check-eq? (interpretCode "tests/4") 16)
(check-eq? (interpretCode "tests/5") 220)
(check-eq? (interpretCode "tests/6") 5)
(check-eq? (interpretCode "tests/7") 6)
(check-eq? (interpretCode "tests/8") 10)
(check-eq? (interpretCode "tests/9") 5)
(check-eq? (interpretCode "tests/10") -39)
(check-exn exn:fail? (lambda () (interpretCode "tests/11")))
(check-exn exn:fail? (lambda () (interpretCode "tests/12")))
(check-exn exn:fail? (lambda () (interpretCode "tests/13")))
(check-exn exn:fail? (lambda () (interpretCode "tests/14")))
(check-eq? (interpretCode "tests/15") 'true)
(check-eq? (interpretCode "tests/16") 100)
(check-eq? (interpretCode "tests/17") 'false)
(check-eq? (interpretCode "tests/18") 'true)
(check-eq? (interpretCode "tests/p1test1") 200)

(display "passed all of tests1\n")

(check-eq? (interpretCode "tests2/1") 100)
(check-eq? (interpretCode "tests2/2") 20)
(check-eq? (interpretCode "tests2/3") 6)
(check-eq? (interpretCode "tests2/4") -1)
(check-eq? (interpretCode "tests2/5") 789)
(check-eq? (interpretCode "tests2/6") 2)
(check-eq? (interpretCode "tests2/7") 164)
(check-exn exn:fail? (lambda () (interpretCode "tests2/8")))
(check-exn exn:fail? (lambda () (interpretCode "tests2/9")))
(check-exn exn:fail? (lambda () (interpretCode "tests2/10")))
(check-eq? (interpretCode "tests2/11") 12)
(check-eq? (interpretCode "tests2/12") 32)

(display "passed all of tests2\n")
