;Logic necessary to run through test suite
(load "interpret.scm")
(load "classParser.scm")
(require rackunit)

(check-eq? (interpretClass "tests4/1" 'A) 10)
(check-eq? (interpretClass "tests4/2" 'A) 'true)
(check-eq? (interpretClass "tests4/3" 'A) 30)
(check-eq? (interpretClass "tests4/4" 'A) 'false)
(check-eq? (interpretClass "tests4/5" 'A) 30)
(check-eq? (interpretClass "tests4/5" 'B) 510)
(check-eq? (interpretClass "tests4/6" 'A) 30)
(check-eq? (interpretClass "tests4/6" 'B) 530)
(check-eq? (interpretClass "tests4/7" 'A) 105)
(check-eq? (interpretClass "tests4/7" 'B) 1155)
(check-eq? (interpretClass "tests4/8" 'B) 615)
(check-exn exn:fail? (lambda () (interpretClass "tests4/9" 'B)))
(check-eq? (interpretClass "tests4/9" 'C) 4321)
(check-eq? (interpretClass "tests4/10" 'Square) 400)
(check-eq? (interpretClass "tests4/11" 'A) 15)
(check-eq? (interpretClass "tests4/12" 'A) 125)
(check-eq? (interpretClass "tests4/13" 'A) 100)
(check-eq? (interpretClass "tests4/14" 'A) 2000400)
(check-eq? (interpretClass "tests4/15" 'Pow) 64)
(check-eq? (interpretClass "tests4/16" 'A) 530)
(check-eq? (interpretClass "tests4/17" 'B) 66)

(display "passed all of tests4\n")