;Logic necessary to run through test suite
(require rackunit)
(load "interpret.scm")

(check-eq? (interpret "tests/1") 150)
(check-eq? (interpret "tests/2") -4)
(check-eq? (interpret "tests/3") 10)
(check-eq? (interpret "tests/4") 16)
(check-eq? (interpret "tests/5") 220)
(check-eq? (interpret "tests/6") 5)
(check-eq? (interpret "tests/7") 6)
(check-eq? (interpret "tests/8") 10)
(check-eq? (interpret "tests/9") 5)
(check-eq? (interpret "tests/10") -39)
(check-exn exn:fail? (lambda () (interpret "tests/11")))
(check-exn exn:fail? (lambda () (interpret "tests/12")))
(check-exn exn:fail? (lambda () (interpret "tests/13")))
(check-exn exn:fail? (lambda () (interpret "tests/14")))
(check-eq? (interpret "tests/15") 'true)
(check-eq? (interpret "tests/16") 100)
(check-eq? (interpret "tests/17") 'false)
(check-eq? (interpret "tests/18") 'true)
